name = "matrix-chatgpt-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
MATRIX_HOMESERVER = "https://matrix.org"

[[kv_namespaces]]
binding = "KV"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[[r2_buckets]]
binding = "R2"
bucket_name = "matrix-bot-storage"
preview_bucket_name = "matrix-bot-storage-preview"

[[durable_objects.bindings]]
name = "MATRIX_SYNC"
class_name = "MatrixSync"
script_name = "matrix-chatgpt-bot"

[[migrations]]
tag = "v1"
new_classes = ["MatrixSync"]

[triggers]
crons = ["*/2 * * * *"]
